### ISSUE TITLE
CMIDecimal is not defined

### ISSUE THREAD

**Issue by natas123** [JohnLeather/LMS-SCORM#1]
Hello
First of all, I would like to congratulate you on this interesting project that you are doing.
I have tested it by uploading a scorm 1.2 course made with storyline 360 and it gives me an error when the course should go to the next slide, I send you a screenshot. I am not very expert but it seems that a function is called in "LMSScorm12RTE.js" CMIDecimal and it is not declared in line 1053.

If you need, he could send you the zip of the course so you can try it.
Greetings and thank you
![bug](https://user-images.githubusercontent.com/417266/121823418-7c2e2080-cca5-11eb-890c-8933041d3c4c.jpg)

**Comment by JohnLeather** [comment]
On line 1053 where it says CMIDecimal it should be this.CMIDecimal

Committed fix.

**Comment by natas123** [comment]
Hi JohnLeather

Perfect, now the problem is solved.
Thank you
